import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://qocupytimtacdrxtqbpc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvY3VweXRpbXRhY2RyeHRxYnBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MjkyMzEsImV4cCI6MjA3MjMwNTIzMX0.kUYpVr0SOXus08j1lxeGipXHNZBoeGT8_JMeXKAAb0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
// // This file is automatically generated. Do not edit it directly.
// import { createClient } from '@supabase/supabase-js';


// const SUPABASE_URL = "https://gjafjcwyvnloiobloktb.supabase.co";
// const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqYWZqY3d5dm5sb2lvYmxva3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDQ5MDQsImV4cCI6MjA3MTEyMDkwNH0.TygY6csC7BEnN0Xk3nb15w1Dif0tZLZl7WVrq0WYKRk";

// // Import the supabase client like this:
// // import { supabase } from "@/integrations/supabase/client";

// export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
//   auth: {
//     storage: localStorage,
//     persistSession: true,
//     autoRefreshToken: true,
//   }
// });